Enforce required alignment with a copy
Copy the XPointer arg, which doesn't have any alignment constraints, to
a XEvent variable, which does have a requirement to align by 8 bytes,
instead of reusing the pointer and inviting misalignment issues.

This fixes the following warning:

    screen.c:88:26: error: cast from 'XPointer' (aka 'char *') to 'XEvent *' (aka 'union _XEvent *') increases required alignment from 1 to 8 [-Werror,-Wcast-align]
       88 |         XEvent* release_event = (XEvent*) arg;
          |                                 ^~~~~~~~~~~~~