Remove any standard setting flags
Rely on the compiler's default C standard definitions instead of
attempting to define our own. This avoids errors like the following:

    misc.c:24:3: error: call to undeclared function 'putenv'; ISO C99 and
    later do not support implicit function declarations
    [-Werror,-Wimplicit-function-declaration]
       24 |                 putenv(current_screen->display);
             |                 ^
             1 error generated.